[build]
command = "yarn install --immutable && yarn build"

[build.environment]
NODE_VERSION = "20.11.0"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[pages]
framework = "nextjs"
pages_build_output_dir = ".next"  # Or "out" if using `next export`

[build.processing]
skip_source_maps = true