[build]
command = "npm install && npm run build"
pages_build_output_dir = "./dist"

[build.environment]
NODE_VERSION = "20.11.0"

[pages]
framework = "nextjs"
pages_build_output_dir = "out"

[build.processing]
skip_source_maps = true